baseURL: 'https://xn--qk8cb8c.ws'
languageCode: 'en-us'
title: 'Â·ğ‘•ğ‘§ğ‘” ğ‘šğ‘¦ğ‘¤ğ‘›ğ‘Ÿ ğ‘© ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ ğ‘¢ğ‘§ğ‘šğ‘•ğ‘²ğ‘‘'
theme: 'PaperMod'
author: 'Â·ğ‘•ğ‘§ğ‘”'

params:
  defaultTheme: "dark"
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  
  homeInfoParams:
    Title: "ğ‘•ğ‘§ğ‘”'ğ‘• ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ ğ‘ğ‘®ğ‘ªğ‘¡ğ‘§ğ‘’ğ‘‘"
    Content: |
      ğŸ‘‹ ğ‘£ğ‘§ğ‘®ğ‘´!
      ğ‘”ğ‘¦ğ‘• ğ‘ğ‘®ğ‘ªğ‘¡ğ‘§ğ‘’ğ‘‘ ğ‘£ğ‘¨ğ‘Ÿ ğ‘ ğ‘“ğ‘ªğ‘¤ğ‘´ğ‘¦ğ‘™ ğ‘œğ‘´ğ‘¤ğ‘Ÿ:
      - ğ‘“ğ‘¹ğ‘• ğ‘¥ğ‘° ğ‘‘ ğ‘¤ğ‘»ğ‘¯ ğ‘‘ ğ‘‘ğ‘²ğ‘ ğ‘¦ğ‘¯ ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯
      - ğ‘šğ‘¦ğ‘¤ğ‘› ğ‘©ğ‘¯ ğ‘§ğ‘¯ğ‘‘ğ‘²ğ‘¼ ğ‘•ğ‘²ğ‘‘ ğ‘¦ğ‘¯ ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯
      - ğ‘œğ‘§ğ‘‘ ğ‘ªğ‘¤ ğ‘šğ‘®ğ‘¬ğ‘Ÿğ‘¼ğ‘Ÿ ğ‘‘ ğ‘›ğ‘¦ğ‘•ğ‘ğ‘¤ğ‘± ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ URL ğ‘¦ğ‘¯ğ‘•ğ‘‘ğ‘§ğ‘› ğ‘ Punycode
      - ğ‘œğ‘§ğ‘‘ Chrome ğ‘‘ ğ‘®ğ‘¦ğ‘¥ğ‘µğ‘ "ğ‘“ğ‘±ğ‘’ ğ‘•ğ‘²ğ‘‘" ğ‘¢ğ‘¹ğ‘¯ğ‘¦ğ‘™
      - ğ‘šğ‘° ğ‘±ğ‘šğ‘©ğ‘¤ ğ‘‘ ğ‘•ğ‘§ğ‘¯ğ‘› ğ‘¯ ğ‘¤ğ‘¦ğ‘•ğ‘°ğ‘ @ğ‘•ğ‘§ğ‘”.com ğ‘°ğ‘¥ğ‘±ğ‘¤  
        
      ğ‘ğ‘¤ğ‘°ğ‘Ÿ ğ‘•ğ‘° ğ‘›ğ‘¦ğ‘•ğ‘’ğ‘±ğ‘¥ğ‘¼ğ‘Ÿ ğ‘ªğ‘¯ ğ‘ [ğ‘©ğ‘šğ‘¬ğ‘‘ ğ‘ğ‘±ğ‘¡](/about)
  assets:
    disableFingerprinting: true
      
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false      
      
menu:
  main:
    - identifier: "posts"
      name: "ğ‘ğ‘´ğ‘•ğ‘‘ğ‘•"
      url: "/posts/"
      weight: 10
    
    - identifier: "about"
      name: "ğ‘©ğ‘šğ‘¬ğ‘‘"
      url: "/about/"
      weight: 20