baseURL: 'https://xn--qk8cb8c.ws'
languageCode: 'en-us'
title: 'Â·ğ‘•ğ‘§ğ‘” ğ‘šğ‘¦ğ‘¤ğ‘›ğ‘Ÿ ğ‘© ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ ğ‘¢ğ‘§ğ‘šğ‘•ğ‘²ğ‘‘'
theme: 'PaperMod'
author: 'Â·ğ‘•ğ‘§ğ‘”'

params:
  defaultTheme: "dark"
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  hideFooter: true
  
  homeInfoParams:
    Title: "Â·ğ‘•ğ‘§ğ‘”'ğ‘• ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ ğ‘¢ğ‘§ğ‘šğ‘•ğ‘²ğ‘‘ ğ‘ğ‘®ğ‘ªğ‘¡ğ‘§ğ‘’ğ‘‘"
    Content: |
      ğ‘£ğ‘§ğ‘®ğ‘´!
      ğ‘”ğ‘¦ğ‘• ğ‘ğ‘®ğ‘ªğ‘¡ğ‘§ğ‘’ğ‘‘ ğ‘£ğ‘¨ğ‘Ÿ ğ‘ ğ‘“ğ‘ªğ‘¤ğ‘´ğ‘¦ğ‘™ ğ‘œğ‘´ğ‘¤ğ‘Ÿ:
      - ~~ğ‘“ğ‘¹ğ‘• ğ‘¥ğ‘° ğ‘‘ ğ‘¤ğ‘»ğ‘¯ ğ‘‘ ğ‘‘ğ‘²ğ‘ ğ‘¦ğ‘¯ ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯~~ (ğ‘² ğ‘£ğ‘¨ğ‘ ğ‘‘ğ‘²ğ‘ğ‘› ğ‘ğ‘¦ğ‘• ğ‘£ğ‘´ğ‘¤ ğ‘•ğ‘²ğ‘‘ ğ‘•ğ‘´ ğ‘¨ğ‘¥ ğ‘’ğ‘ªğ‘¤ğ‘¦ğ‘™ ğ‘ğ‘¦ğ‘• ğ‘›ğ‘³ğ‘¯)
      - ~~ğ‘šğ‘¦ğ‘¤ğ‘› ğ‘©ğ‘¯ ğ‘§ğ‘¯ğ‘‘ğ‘²ğ‘¼ ğ‘•ğ‘²ğ‘‘ ğ‘¦ğ‘¯ ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯~~ (ğ‘¨ğ‘¤ ğ‘‘ğ‘§ğ‘’ğ‘‘ğ‘• ğ‘¦ğ‘Ÿ ğ‘¦ğ‘¯ ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯, ğ‘¦ğ‘¯ğ‘’ğ‘¤ğ‘µğ‘›ğ‘¦ğ‘™ ğ‘›ğ‘±ğ‘‘ğ‘• ğ‘¯ URLs, ğ‘•ğ‘´ ğ‘¨ğ‘¥ ğ‘’ğ‘ªğ‘¤ğ‘¦ğ‘™ ğ‘ğ‘¦ğ‘• ğ‘›ğ‘³ğ‘¯) 
      - ğ‘œğ‘§ğ‘‘ ğ‘ªğ‘¤ ğ‘šğ‘®ğ‘¬ğ‘Ÿğ‘¼ğ‘Ÿ ğ‘‘ ğ‘›ğ‘¦ğ‘•ğ‘ğ‘¤ğ‘± ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ URL ğ‘¦ğ‘¯ğ‘•ğ‘‘ğ‘§ğ‘› ğ‘ Punycode
      - ğ‘œğ‘§ğ‘‘ Chrome ğ‘‘ ğ‘®ğ‘¦ğ‘¥ğ‘µğ‘ "ğ‘“ğ‘±ğ‘’ ğ‘•ğ‘²ğ‘‘" ğ‘¢ğ‘¹ğ‘¯ğ‘¦ğ‘™
      - ~~ğ‘° ğ‘±ğ‘šğ‘©ğ‘¤ ğ‘‘ ğ‘•ğ‘§ğ‘¯ğ‘› ğ‘¯ ğ‘¤ğ‘¦ğ‘•ğ‘°ğ‘ @ğ‘•ğ‘§ğ‘”.ws ğ‘°ğ‘¥ğ‘±ğ‘¤~~ (ğ‘’ğ‘©ğ‘¥ğ‘ğ‘¤ğ‘°ğ‘‘! ğ‘•ğ‘° ğ‘³ğ‘ğ‘›ğ‘±ğ‘‘ [ğ‘£ğ‘½](/ğ‘ğ‘´ğ‘•ğ‘‘ğ‘•/2024-12-03-ğ‘°ğ‘¥ğ‘±ğ‘¤-ğ‘¨ğ‘Ÿ-ğ‘œğ‘«ğ‘›-ğ‘¨ğ‘Ÿ-ğ‘¦ğ‘‘-ğ‘’ğ‘¨ğ‘¯-ğ‘œğ‘§ğ‘‘))
        
      ğ‘ğ‘¤ğ‘°ğ‘Ÿ ğ‘•ğ‘° ğ‘›ğ‘¦ğ‘•ğ‘’ğ‘±ğ‘¥ğ‘¼ğ‘Ÿ ğ‘ªğ‘¯ ğ‘ [ğ‘©ğ‘šğ‘¬ğ‘‘ ğ‘ğ‘±ğ‘¡](/ğ‘©ğ‘šğ‘¬ğ‘‘/)
  assets:
    disableFingerprinting: true
      
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false      
      
menu:
  main:
    - identifier: "ğ‘ğ‘´ğ‘•ğ‘‘ğ‘•"
      name: "ğ‘ğ‘´ğ‘•ğ‘‘ğ‘•"
      url: "/ğ‘ğ‘´ğ‘•ğ‘‘ğ‘•/"
      weight: 10
    
    - identifier: "ğ‘©ğ‘šğ‘¬ğ‘‘"
      name: "ğ‘©ğ‘šğ‘¬ğ‘‘"
      url: "/ğ‘©ğ‘šğ‘¬ğ‘‘/"
      weight: 20
      
    - identifier: "ğ‘¢ğ‘»ğ‘’ğ‘¦ğ‘™-ğ‘¹-ğ‘¯ğ‘ªğ‘‘"
      name: "ğ‘¢ğ‘»ğ‘’ğ‘¦ğ‘™ ğ‘¹ ğ‘¯ğ‘ªğ‘‘"
      url: "/ğ‘¢ğ‘¹ğ‘’ğ‘¦ğ‘™-ğ‘¹-ğ‘¯ğ‘ªğ‘‘/"
      weight: 30