baseURL = 'https://xn--qk8cb8c.ws'
languageCode = 'en-us'
title = 'Â·ğ‘•ğ‘§ğ‘” ğ‘šğ‘¦ğ‘¤ğ‘›ğ‘Ÿ ğ‘© ğ‘–ğ‘±ğ‘ğ‘¾ğ‘¯ ğ‘¢ğ‘§ğ‘šğ‘•ğ‘²ğ‘‘'
theme = 'PaperMod'

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true

[[menu.main]]
identifier = "posts"
name = "ğ‘ğ‘´ğ‘•ğ‘‘ğ‘•"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "ğ‘©ğ‘šğ‘¬ğ‘‘"
url = "/about/"
weight = 20